# Ex2 - Getting and Knowing your Data

### Step 1. Import the necessary libraries

In [26]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv).

### Step 3. Assign it to a variable called chipo.

In [27]:
chipo = pd.read_csv("https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv",sep="\t")
chipo

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

### Step 4. See the first 10 entries

In [28]:
chipo.head()

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98

### Step 5. What is the number of observations in the dataset?

In [29]:
# Solution 1
x = len(chipo)

print("Number of observations:", x)

Number of observations: 4622

In [30]:
# Solution 2

x = chipo.shape[0]

print("Number of observations:", x)

Number of observations: 4622

### Step 6. What is the number of columns in the dataset?

In [31]:
x = chipo.shape[1]

print("Number of columns:", x)

Number of columns: 5

### Step 7. Print the name of all the columns.

In [32]:
chipo.columns

Index(['order_id', 'quantity', 'item_name', 'choice_description',
       'item_price'],
      dtype='object')

### Step 8. How is the dataset indexed?

In [33]:
chipo.index

RangeIndex(start=0, stop=4622, step=1)

### Step 9. Which was the most-ordered item?

In [34]:
chipo['item_name'].value_counts().sort_values(ascending=False).head(1)

Chicken Bowl    726
Name: item_name, dtype: int64

### Step 10. For the most-ordered item, how many items were ordered?

In [35]:
max_ordered_quantity = chipo.groupby('item_name')['quantity'].sum().max()
max_ordered_quantity

761

### Step 11. What was the most ordered item in the choice_description column?

In [36]:
most_ordered_item = chipo.groupby('choice_description')['quantity'].sum().idxmax()
most_ordered_item

'[Diet Coke]'

### Step 12. How many items were orderd in total?

In [37]:
items_were_orderd = chipo['quantity'].sum()
items_were_orderd

4972

### Step 13. Turn the item price into a float

In [38]:
chipo['item_price'] = chipo['item_price'].str.replace('$', '').astype(float)

# Verify the data type conversion
print(chipo['item_price'].dtype)

float64

C:\Users\Ahmed\AppData\Local\Temp\ipykernel_21084\2832234341.py:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  chipo['item_price'] = chipo['item_price'].str.replace('$', '').astype(float)

#### Step 13.a. Check the item price type

In [39]:
chipo['item_price'].dtype

dtype('float64')

#### Step 13.b. Create a lambda function and change the type of item price

In [40]:
#convert_to_float = lambda x: float(x.replace('$', ''))

#chipo['item_price'] = chipo['item_price'].apply(convert_to_float)

#### Step 13.c. Check the item price type

In [41]:
chipo['item_price'].dtype

dtype('float64')

### Step 14. How much was the revenue for the period in the dataset?

In [42]:
x = chipo['item_price'] * chipo['quantity']
print(f"the revenue : {x.sum()}")

the revenue : 39237.02

### Step 15. How many orders were made in the period?

In [43]:
x = chipo['order_id'].nunique()

print(f"Number of orders : {x}")

Number of orders : 1834

### Step 16. What is the average revenue amount per order?

In [44]:
# Solution 1
order_revenue = chipo.groupby('order_id')['item_price'].sum().mean()

print("Average Revenue per Order: $", order_revenue)

Average Revenue per Order: $ 18.811428571428568

In [46]:
# Solution 2

#total_revenue = chipo['revenue'].sum()
#total_orders = chipo['order_id'].nunique()

#average_revenue_per_order = total_revenue / total_orders
#print(f"Average revenue amount per order: {average_revenue_per_order}$")

### Step 17. How many different items are sold?

In [ ]:
unique_items = chipo['item_name'].nunique()
unique_items

50